name: CI/CD Pipeline

on:
  push:
    [cite_start]branches: [ master ] [cite: 80]

jobs:
  test:
    [cite_start]name: Run Unit Tests [cite: 23]
    [cite_start]runs-on: ubuntu-latest [cite: 24]
    steps:
      - [cite_start]uses: actions/checkout@v4 [cite: 27]
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - [cite_start]name: Run Tests [cite: 86]
        run: dotnet test --no-build --verbosity normal
        env:
          # Передаем строку подключения из секретов GitHub для тестов (если нужно) [cite: 113]
          CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}

  build:
    [cite_start]name: Build and Push Image [cite: 87]
    [cite_start]needs: test # Сборка начнется только если тесты прошли (зеленые) [cite: 44]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      [cite_start]packages: write [cite: 48]
    steps:
      - [cite_start]uses: actions/checkout@v4 [cite: 50]
      
      - [cite_start]name: Log in to GHCR [cite: 91]
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - [cite_start]name: Build and push [cite: 93]
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest